version: '3.8'
services:
  nginx:
    build: ./nginx
    ports:
      - "8443:443"
    networks:
      - inception_network
    depends_on:
      - wordpress
      - mariadb
    restart: always

  wordpress:
    build: ./wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
    restart: always

  mariadb:
    image: ./mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always

volumes:
  wordpress_data:
  mariadb_data:

networks:
  inception_network: