version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
    - "${NGINX_PORT}:${NGINX_PORT}"
    networks:
    - inception
    volumes:
    - wordpress_data:/var/www/html
  wordpress:
   build: requirements/wordpress/.
   container_name: wordpress
   expose:
    - "${WORDPRESS_PORT}"
   environment:
    WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
    WORDPRESS_DB_PORT: ${WORDPRESS_DB_PORT}
    WORDPRESS_ROOT: ${WORDPRESS_ROOT}
    WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
    WORDPRESS_USER: ${WORDPRESS_USER}
    WORDPRESS_WEBSITE: ${WORDPRESS_WEBSITE}
    WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    WORDPRESS_DB_PASSWORD_FILE: /run/secrets/wordpress_db_password
    WORDPRESS_ADMIN_PASSWORD_FILE: /run/secrets/wordpress_admin_password
    WORDPRESS_USER_PASSWORD_FILE: /run/secrets/wordpress_user_password
   secrets:
    - wordpress_db_password
    - wordpress_admin_password
    - wordpress_user_password
   healthcheck:
      test: curl -f "${WORDPRESS_WEBSITE}:9000" || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
   networks:
    - inception
   volumes:
    - wordpress_data:/var/www/html
  mariadb:
   build: requirements/mariadb/.
   container_name: mariadb
   environment:
    MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    MYSQL_DATABASE: ${MYSQL_DATABASE}
    MYSQL_USER: ${MYSQL_ROOT_USER}
    MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
   secrets:
   - mysql_root_password
   - mysql_password
   networks:
    - inception
   volumes:
    - mariadb_data:/var/lib/mysql
secrets:
  mysql_password:
   file: ../secrets/mysql_password.txt
  mysql_root_password:
   file: ../secrets/mysql_root_password.txt
  wordpress_db_password:
   file: ../secrets/wordpress_db_password.txt
  wordpress_admin_password:
   file: ../secrets/wordpress_admin_password.txt
  wordpress_user_password:
   file: ../secrets/wordpress_user_password.txt
networks:
  inception:
    name: inception
    driver: bridge
volumes:
  mariadb_data:
    name: mariadb
    driver: local
    driver_opts:
     type: none
     o: bind
     device: /home/${LOGIN}/data/mariadb
  wordpress_data:
    name: wordpress
    driver: local
    driver_opts:
     type: none
     o: bind
     device: /home/${LOGIN}/data/wordpress