version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
    - "443:443"
    networks:
    - inception
    volumes:
    - data:/var/www/html
  wordpress:
   build: requirements/wordpress/.
   container_name: wp-php
   expose:
    - "9000"
   environment:
    WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
    WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
    WORDPRESS_DB_PASSWORD_FILE: /run/secrets/wordpress_db_password
    WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
   secrets:
    - wordpress_db_password
   healthcheck:
      test: ["CMD", "curl", "-f", "https://tnakas.42.fr:9000"]
      interval: 10s
      timeout: 5s
      retries: 3
   networks:
    - inception
   volumes:
    - data:/var/www/html
  mariadb:
   build: requirements/mariadb/.
#    image: mariadb:10.5
   container_name: db
   environment:
    MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    MYSQL_DATABASE: ${MYSQL_DATABASE}
    MYSQL_USER: ${MYSQL_ROOT_USER}
    MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
   secrets:
   - mysql_root_password
   - mysql_password
   networks:
    - inception
   volumes:
    - db_data:/var/lib/mysql
secrets:
  mysql_password:
   file: ../secrets/mysql_password.txt
  mysql_root_password:
   file: ../secrets/mysql_root_password.txt
  wordpress_db_password:
   file: ../secrets/wordpress_db_password.txt
networks:
  inception:
    driver: bridge
volumes:
  db_data:
  data:

# database_name: wp_db
# username: wp_root_user
# password: L3@rner
# database_host: db