version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: maria_db
    networks:
      - inception
    restart: unless-stopped
    # volumes:
    #   - ${HOME}/data/mariadb/:/var/lib/mysql
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - SECURE_ADMIN_PASSWORD_FILE=/run/secrets/admin_password
      - SECURE_EDITOR_PASSWORD_FILE=/run/secrets/editor_password
    secrets:
      - mysql_root_password
      - mysql_password
      - admin_password
      - editor_password

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    restart: unless-stopped
    # volumes:
    #   - ${HOME}/data/wordpress:/var/www/html
    # I should comment this when I am in VM
    volumes:
      - wp_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=maria_db
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/mysql_password
    secrets:
      - mysql_password
  nginx:
    build:  ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: unless-stopped
    volumes:

      # - ${HOME}/data/wordpress:/var/www/html
      # I should comment this when I am in VM
      - wp_data:/var/www/html
      - ./requirements/nginx/tools/ssl:/etc/nginx/ssl
networks:
  inception:
    driver: bridge
secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_password:
    file: ./secrets/mysql_password.txt
  admin_password:
    file: ./secrets/admin_password.txt
  editor_password:
    file: ./secrets/editor_password.txt
# I should comment this when I am in VM
volumes:
  mariadb_data:
  wp_data:
