version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: maria_db
    networks:
      - inception
    restart: unless-stopped
    volumes:
      - ${HOME}/data/mariadb/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${WP_DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${WP_DB_DATABASE}
      - MYSQL_USER=${WP_DB_USER}
      - MYSQL_PASSWORD=${WP_DB_PASSWORD}
      - SECURE_ADMIN_PASSWORD=${SECURE_ADMIN_PASSWORD}
      - SECURE_EDITOR_PASSWORD=${SECURE_EDITOR_PASSWORD}
    secrets:
      - db_root_password
      - db_password
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - maria_db
    restart: unless-stopped
    volumes:
      - ${HOME}/data/wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    secrets:
      - db_password
  nginx:
    build:  ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: unless-stopped
    volumes:
      - ${HOME}/data/wordpress:/var/www/html
      - ./requirements/nginx/tools/ssl:/etc/nginx/ssl
networks:
  inception: